export const riddles = [
    {"riddle":"It is greater than God and more evil than the devil. The poor have it, the rich need it and if you eat it you’ll die. What is it?","answer":"Nothing"},
    {"riddle":"It walks on four legs in the morning, two legs at noon and three legs in the evening. What is it?","answer":"Man"},
    {"riddle":"I am the beginning of the end, and the end of time and space. I am essential to creation, and I surround every place. What am I?","answer":"The letter 'E'"},
    {"riddle":"What always runs but never walks, often murmurs, never talks, has a bed but never sleeps, has a mouth but never eats?","answer":"a river"},
    {"riddle":"I never was, am always to be. No one ever saw me, nor ever will. And yet I am the confidence of all, To live and breath on this terrestrial ball. What am I?","answer":"Tomorrow or the Future"},
    {"riddle":"At night they come without being fetched. By day they are lost without being stolen. What are they?","answer":"The stars."},
    {"riddle":"What is in seasons, seconds, centuries and minutes but not in decades, years or days?","answer":"The letter 'N'"},
    {"riddle":"The one who makes it, sells it. The one who buys it, never uses it. The one that uses it never knows that he’s using it. What is it?","answer":"a coffin"},
    {"riddle":"The more you have of it, the less you see. What is it?","answer":"Darkness"},
    {"riddle":"What has a head, a tail, is brown, and has no legs?","answer":"a penny"},
    {"riddle":"What English word has three consecutive double letters?","answer":"Bookkeeper"},
    {"riddle":"What’s black when you get it, red when you use it, and white when you’re all through with it?","answer":"Charcoal"},
    {"riddle":"You throw away the outside and cook the inside. Then you eat the outside and throw away the inside. What did you eat?","answer":"An ear of corn"},
    {"riddle":"I am always hungry, I must always be fed, The finger I touch, Will soon turn red","answer":"Fire"},
    {"riddle":"Ripped from my mother’s womb, Beaten and burned, I become a blood thirsty killer. What am I?","answer":"Iron ore"},
    {"riddle":"I know a word of letters three. Add two, and fewer there will be!","answer":"Few"},
    {"riddle":"I give you a group of three. One is sitting down, and will never get up. The second eats as much as is given to him, yet is always hungry. The third goes away and never returns.","answer":"Stove, fire, smoke"},
    {"riddle":"I have four legs but no tail. Usually I am heard only at night. What am I?","answer":"a frog"},
    {"riddle":"Half-way up the hill, I see thee at last, lying beneath me with thy sounds and sights — A city in the twilight, dim and vast, with smoking roofs, soft bells, and gleaming lights.","answer":"the past"},
    {"riddle":"When young, I am sweet in the sun. When middle-aged, I make you gay. When old, I am valued more than ever.","answer":"Wine"},
    {"riddle":"All about, but cannot be seen, Can be captured, cannot be held, No throat, but can be heard.","answer":"Wind"},
    {"riddle":"If you break me, I do not stop working, If you touch me, I may be snared, If you lose me, Nothing will matter.","answer":"Your heart"},
    {"riddle":"Until I am measured I am not known, Yet how you miss me when I have flown.","answer":"Time"},
    {"riddle":"I drive men mad. For love of me, Easily beaten, Never free.","answer":"Gold"},
    {"riddle":"When set loose, I fly away, Never so cursed, As when I go astray.","answer":"a fart"},
    {"riddle":"Lighter than what I am made of, More of me is hidden Than is seen.","answer":"Iceberg"},
    {"riddle":"Each morning I appear to lie at your feet, All day I will follow no matter how fast you run, Yet I nearly perish in the midday sun.","answer":"Shadow"},
    {"riddle":"My life can be measured in hours, I serve by being devoured. Thin, I am quick. Fat, I am slow. Wind is my foe.","answer":"a candle"},
    {"riddle":"I am seen in the water if seen in the sky, I am in the rainbow, a jay’s feather,and lapis lazuli.","answer":"Blue"},
    {"riddle":"Glittering points that downward thrust, Sparkling spears that never rust.","answer":"Icicle"},
    {"riddle":"You heard me before, yet you hear me again, Then I die, ’till you call me again.","answer":"An echo"},
    {"riddle":"Three lives have I. Gentle enough to soothe the skin, Light enough to caress the sky, Hard enough to crack rocks.","answer":"Water"},
    {"riddle":"At the sound of me, men may dream or stamp their feet, At the sound of me, women may laugh or sometimes weep.","answer":"Music"},
    {"riddle":"What does man love more than life, Fear more than death or mortal strife, What the poor have, the rich require, and what contented men desire, What the miser spends and the spendthrift saves. And all men carry to their graves?","answer":"Nothing"},
    {"riddle":"I build up castles. I tear down mountains. I make some men blind, I help others to see. What am I?","answer":"Sand"},
];